DO $$
DECLARE
    side_dish_category_id INT;
BEGIN
    SELECT id INTO side_dish_category_id FROM categories WHERE name = 'Гарниры';
    INSERT INTO dishes (name, price, category_id) VALUES
    ('Брокколи отварные', 65, side_dish_category_id),
    ('Булгур', 45, side_dish_category_id),
    ('Булгур отварной', 45, side_dish_category_id),
    ('Гречка', 30, side_dish_category_id),
    ('Гречка по-купечески', 45, side_dish_category_id),
    ('Гречка по-купечески с грибами', 45, side_dish_category_id),
    ('Гречка с овощами', 32, side_dish_category_id),
    ('Гречка с овощами и грибами', 35, side_dish_category_id),
    ('Гречка с овощами с подливой', 32, side_dish_category_id),
    ('Гречка с подливой', 30, side_dish_category_id),
    ('Капуста тушеная', 35, side_dish_category_id),
    ('Капуста цветная отварная', 65, side_dish_category_id),
    ('Картофель жаренный', 40, side_dish_category_id),
    ('Картофель жареный с грибами', 45, side_dish_category_id),
    ('Картофель запеченный с грибами', 45, side_dish_category_id),
    ('Картофель запеченный с сыром', 45, side_dish_category_id),
    ('Картофель запеченный с сыром и майонезом', 45, side_dish_category_id),
    ('Картофель запеченный со сметаной и сыром', 45, side_dish_category_id),
    ('Картофель отварной', 35, side_dish_category_id),
    ('Картофель отварной с зеленью', 35, side_dish_category_id),
    ('Картофель отварной с укропом и чесноком', 35, side_dish_category_id),
    ('Картофель с грибами', 45, side_dish_category_id),
    ('Картофельное пюре', 35, side_dish_category_id),
    ('Картофельные дольки', 40, side_dish_category_id),
    ('Картофельные дольки запеченные', 45, side_dish_category_id),
    ('Картофельные дольки с кетчупом', 50, side_dish_category_id),
    ('Каша гороховая', 30, side_dish_category_id),
    ('Каша овсяная', 30, side_dish_category_id),
    ('Каша овсяная молочная', 30, side_dish_category_id),
    ('Каша пшеничная', 30, side_dish_category_id),
    ('Каша пшенная', 30, side_dish_category_id),
    ('Каша рисовая молочная', 40, side_dish_category_id),
    ('Лапша', 30, side_dish_category_id),
    ('Лапша в томатном соусе', 35, side_dish_category_id),
    ('Лапша с грибами и овощами', 35, side_dish_category_id),
    ('Лапша с овощами', 35, side_dish_category_id),
    ('Лапша с овощами и шампиньонами', 45, side_dish_category_id),
    ('Лапша с соевым соусом', 35, side_dish_category_id),
    ('Лапша с томатным соусом под сыром', 32, side_dish_category_id),
    ('Лапша с шампиньонами и овощами', 40, side_dish_category_id),
    ('Макароны', 25, side_dish_category_id),
    ('Макароны с песто', 30, side_dish_category_id),
    ('Макароны с подливой', 25, side_dish_category_id),
    ('Макароны с сыром', 30, side_dish_category_id),
    ('Овощное рагу', 40, side_dish_category_id),
    ('Перловка отварная', 30, side_dish_category_id),
    ('Перловка с овощами', 32, side_dish_category_id),
    ('Рис', 40, side_dish_category_id),
    ('Рис отварной', 30, side_dish_category_id),
    ('Рис с овощами', 35, side_dish_category_id),
    ('Рис со стручковой фасолью', 37, side_dish_category_id),
    ('Рис шафран', 40, side_dish_category_id),
    ('Фасоль стручковая жаренная', 65, side_dish_category_id);
END $$;
