version: '3.1'
services:
 db:
   image: postgres
   restart: always
   ports:
     - ${POSTGRES_PORT}:5432
   environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password not set}
     POSTGRES_DB: ${POSTGRES_DB}
   volumes:
     - postgres-data:/var/lib/postgresql/data
volumes:
 postgres-data:
