services:
 db:
   image: postgres
   restart: always
   ports:
     - 5433:5432
   environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password not set}
   volumes:
     - postgres-data:/var/lib/postgresql/data
volumes:
 postgres-data: