version: '3'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:${HTTP_SERVER_PORT}"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
    # depends_on:
    #   - db

  cli:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: cli
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    # depends_on:
    #   - db
    profiles:
      - cli      

  # frontend:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   environment:
  #     - API_URL=http://backend:${HTTP_SERVER_PORT}

  # db:
  #   image: postgres:16.6
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: always

volumes:
  postgres-data:
